version: '3' 
services:
  mongodb:
   image: mongo 
   volumes:
     - ./mongo-data:/data/db
  
  nats:
   image: nats 

   
  nest_docker:
   image: nest_docker
   ports:
     - 3700:3700
   depends_on:
     - mongodb
     - nats 
  
  go-docker:
   image: go-docker
   ports:
     - 3600:3600
   depends_on:
     - nats 
  